import { Link } from 'react-router-dom'

export default function TermsAndConditions() {
  return (
    <div className="bg-white">
      <div className="w-full bg-gray-100">
        <div className="w-full px-8 py-10 text-center sm:px-12 md:px-8 lg:px-14">
          <div className="text-2xl font-semibold text-gray-900 sm:text-3xl md:text-4xl">Terms and Conditions</div>
          <div className="mt-2 text-xs font-semibold text-gray-600 sm:text-sm md:text-base">
            Please read these terms carefully before using our website.
          </div>
        </div>
      </div>

      <div className="w-full px-8 py-10 sm:px-12 md:px-8 lg:px-14">
        <div className="mx-auto max-w-4xl space-y-8 text-sm text-gray-700 sm:text-base">
          <div className="space-y-3">
            <div className="text-base font-semibold text-gray-900 sm:text-lg">Electronic Record & Terms of Use</div>
            <div>
              This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as
              applicable and the amended provisions pertaining to electronic records in various statutes as amended by
              the Information Technology Act, 2000. This electronic record is generated by a computer system and does
              not require any physical or digital signatures.
            </div>
            <div>
              This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology
              (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy
              and Terms of Use for access or usage of domain name https://suman925silver.in/ (&apos;Website&apos;),
              including the related mobile site and mobile application (hereinafter referred to as &apos;Platform&apos;).
            </div>
            <div>
              The Platform is owned by Suman Gold Refinery, a company incorporated under the Companies Act, 1956 with its
              registered office at Raviwar Peth, Pune, Maharashtra, 411002 (hereinafter referred to as ‘Platform Owner’,
              &apos;we&apos;, &apos;us&apos;, &apos;our&apos;).
            </div>
            <div>
              Your use of the Platform and services and tools are governed by the following terms and conditions (“Terms
              of Use”) as applicable to the Platform including the applicable policies which are incorporated herein by
              way of reference. If You transact on the Platform, You shall be subject to the policies that are
              applicable to the Platform for such transaction. By mere use of the Platform, You shall be contracting
              with the Platform Owner and these terms and conditions including the policies constitute Your binding
              obligations, with Platform Owner. These Terms of Use relate to your use of our website, goods (as
              applicable) or services (as applicable) (collectively, &apos;Services&apos;). Any terms and conditions
              proposed by You which are in addition to or which conflict with these Terms of Use are expressly rejected
              by the Platform Owner and shall be of no force or effect. These Terms of Use can be modified at any time
              without assigning any reason. It is your responsibility to periodically review these Terms of Use to stay
              informed of updates.
            </div>
            <div>
              For the purpose of these Terms of Use, wherever the context so requires ‘you’, &apos;your&apos; or ‘user’
              shall mean any natural or legal person who has agreed to become a user/buyer on the Platform.
            </div>
            <div className="font-semibold text-gray-900">
              ACCESSING, BROWSING OR OTHERWISE USING THE PLATFORM INDICATES YOUR AGREEMENT TO ALL THE TERMS AND
              CONDITIONS UNDER THESE TERMS OF USE, SO PLEASE READ THE TERMS OF USE CAREFULLY BEFORE PROCEEDING.
            </div>
            <div>The use of Platform and/or availing of our Services is subject to the following Terms of Use:</div>
            <ul className="list-disc space-y-2 pl-5">
              <li>
                To access and use the Services, you agree to provide true, accurate and complete information to us
                during and after registration, and you shall be responsible for all acts done through the use of your
                registered account on the Platform.
              </li>
              <li>
                Neither we nor any third parties provide any warranty or guarantee as to the accuracy, timeliness,
                performance, completeness or suitability of the information and materials offered on this website or
                through the Services, for any specific purpose. You acknowledge that such information and materials may
                contain inaccuracies or errors and we expressly exclude liability for any such inaccuracies or errors to
                the fullest extent permitted by law.
              </li>
              <li>
                Your use of our Services and the Platform is solely and entirely at your own risk and discretion for
                which we shall not be liable to you in any manner. You are required to independently assess and ensure
                that the Services meet your requirements.
              </li>
              <li>
                The contents of the Platform and the Services are proprietary to us and are licensed to us. You will not
                have any authority to claim any intellectual property rights, title, or interest in its contents. The
                contents includes and is not limited to the design, layout, look and graphics.
              </li>
              <li>
                You acknowledge that unauthorized use of the Platform and/or the Services may lead to action against you
                as per these Terms of Use and/or applicable laws.
              </li>
              <li>You agree to pay us the charges associated with availing the Services.</li>
              <li>
                You agree not to use the Platform and/ or Services for any purpose that is unlawful, illegal or
                forbidden by these Terms, or Indian or local laws that might apply to you.
              </li>
              <li>
                You agree and acknowledge that website and the Services may contain links to other third party websites.
                On accessing these links, you will be governed by the terms of use, privacy policy and such other
                policies of such third party websites. These links are provided for your convenience for provide further
                information.
              </li>
              <li>
                You understand that upon initiating a transaction for availing the Services you are entering into a
                legally binding and enforceable contract with the Platform Owner for the Services.
              </li>
              <li>
                You shall indemnify and hold harmless Platform Owner, its affiliates, group companies (as applicable)
                and their respective officers, directors, agents, and employees, from any claim or demand, or actions
                including reasonable attorney&apos;s fees, made by any third party or penalty imposed due to or arising out
                of Your breach of this Terms of Use, privacy Policy and other Policies, or Your violation of any law,
                rules or regulations or the rights (including infringement of intellectual property rights) of a third
                party.
              </li>
              <li>
                Notwithstanding anything contained in these Terms of Use, the parties shall not be liable for any
                failure to perform an obligation under these Terms if performance is prevented or delayed by a force
                majeure event.
              </li>
              <li>
                These Terms and any dispute or claim relating to it, or its enforceability, shall be governed by and
                construed in accordance with the laws of India.
              </li>
              <li>All disputes arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts in and .</li>
              <li>
                All concerns or communications relating to these Terms must be communicated to us using the contact
                information provided on this website.
              </li>
            </ul>
          </div>

          <div className="space-y-2">
            <div className="text-base font-semibold text-gray-900 sm:text-lg">1. Acceptance of terms</div>
            <div>
              By accessing or using this website, you agree to be bound by these Terms and Conditions and all applicable
              laws and regulations.
            </div>
          </div>

          <div className="space-y-2">
            <div className="text-base font-semibold text-gray-900 sm:text-lg">2. Products and pricing</div>
            <div>
              Product images are for illustration purposes. Prices, availability, and specifications may change without
              notice. We reserve the right to cancel any order in case of pricing or listing errors.
            </div>
          </div>

          <div className="space-y-2">
            <div className="text-base font-semibold text-gray-900 sm:text-lg">3. Orders and payments</div>
            <div>
              An order is confirmed only after successful payment (where applicable) and confirmation. We may request
              additional verification for certain transactions.
            </div>
          </div>

          <div className="space-y-2">
            <div className="text-base font-semibold text-gray-900 sm:text-lg">4. Shipping and delivery</div>
            <div>
              Delivery timelines are estimates and may vary due to location, courier constraints, or other factors beyond
              our control.
            </div>
            <div className="font-semibold text-gray-800">
              See: <Link to="/shipping-policy" className="text-[#0f2e40] underline">Shipping Policy</Link>
            </div>
          </div>

          <div className="space-y-2">
            <div className="text-base font-semibold text-gray-900 sm:text-lg">5. Returns and refunds</div>
            <div>
              Returns and refunds (if any) are governed by our policies.
            </div>
            <div className="font-semibold text-gray-800">
              See:{' '}
              <Link to="/return-policy" className="text-[#0f2e40] underline">
                Return Policy
              </Link>{' '}
              and{' '}
              <Link to="/refund-policy" className="text-[#0f2e40] underline">
                Refund Policy
              </Link>
            </div>
          </div>

          <div className="space-y-2">
            <div className="text-base font-semibold text-gray-900 sm:text-lg">6. Privacy</div>
            <div>
              We respect your privacy and process personal data as described in our Privacy Policy.
            </div>
            <div className="font-semibold text-gray-800">
              See: <Link to="/privacy-policy" className="text-[#0f2e40] underline">Privacy Policy</Link>
            </div>
          </div>

          <div className="rounded-xl bg-gray-50 p-5 ring-1 ring-gray-200">
            <div className="text-sm font-semibold text-gray-900">Policies</div>
            <div className="mt-2 text-sm text-gray-700">
              For a full list of policies, visit{' '}
              <Link to="/policies" className="font-semibold text-[#0f2e40] underline">
                Policies
              </Link>
              .
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
